### ISSUE TITLE
 Can add tabline support and perfect eleline

### ISSUE THREAD

**Issue by glepnir** [liuchengxu/eleline.vim#15]
## Feature
是否可以添加tabline支持，从airline切换过来使用没有tabline，虽然我可以通过命令映射在buffer之间跳转，但是我更希望能在顶部看到所打开的buffer就像airline tabline一样。找了一些相关插件，过于复杂，它应该是轻量的
## Problem
truecolor 下颜色偏暗了，256下橙黄很好看，我安装了spacemacs进行对比，差异还是很多，以下对比。
spacemacs
![42](https://user-images.githubusercontent.com/41671631/52051027-4df48e00-258d-11e9-8d67-105ddafb24b4.png)
eleline 我的环境
![1112](https://user-images.githubusercontent.com/41671631/52051039-58168c80-258d-11e9-99d4-fafc69429e51.png)
是否有必要进一步修改eleline，使得更加像spacemacs。如果不方便我会fork进行尝试

**Comment by liuchengxu** [comment]
eleline.vim 只是神似 spacemacs, 取了一些我觉得不错又简单的元素，并不是原版照搬。有时间的话，你完全可以做一个跟 spacemacs 一模一样的状态栏，实现没什么难的，但注意除了美观，最好兼具性能。关于这个插件，我目前没有更多打算。

关于颜色这一点，欢迎 PR。

**Comment by glepnir** [comment]
> eleline.vim 只是神似 spacemacs, 取了一些我觉得不错又简单的元素，并不是原版照搬。有时间的话，你完全可以做一个跟 spacemacs 一模一样的状态栏，实现没什么难的，但注意除了美观，最好兼具性能。关于这个插件，我目前没有更多打算。
> 
> 关于颜色这一点，欢迎 PR。

好的，我会尝试做一个差不多的，我在查找一些关于statusline的资料进行尝试，statusline里的形状是需要通过powerline或者nerdfont来制作吗？像spacemacs中的梯形等形状。我会基于你的fork修改，因为它支持了ale coc等我日常用到的插件很好的进行语法检测。我用不到的功能性能我想我目前不会考虑。我会关闭这个issue进行尝试。
