### ISSUE TITLE
buffer 信息显示

### ISSUE THREAD

**Issue by ghost** [liuchengxu/eleline.vim#16]
能否添加一个选项，用来控制buffer信息的显示？

**Comment by liuchengxu** [comment]
你想怎么控制？

**Comment by ghost** [comment]
①  ❖ 1 [TOT:1]  就是这个，能不能让使用者选择性的开启 或者可以定制显示的内容

**Comment by liuchengxu** [comment]
`let g:eleline_slim = 1` 就会只显示 ① ❖ 1

**Comment by liuchengxu** [comment]
如果想要更多定制内容，可以选择 fork。因为每个人都有自己的偏好，我不想为每个需求都增加一个配置项，这个插件非常小，本身就不具备强定制化的功能。 fork 的话，基本上改这里就行了：

https://github.com/liuchengxu/eleline.vim/blob/be06b337f28faf5d6a523f17bb05c99c2f1e91fb/plugin/eleline.vim#L185-L213

return 什么就会在状态栏显示什么。

**Comment by ghost** [comment]
嗯嗯，是的，我现在就是直接return空，这么晚了还回复的这么及时，真是辛苦啦，谢谢
