### ISSUE TITLE
能不能在状态栏显示当前函数呀

### ISSUE THREAD

**Issue by ghost** [liuchengxu/eleline.vim#17]
我刚开始想自己加上呢，但是不知道怎么获取到当前所在函数，所以，厚颜提下

**Comment by liuchengxu** [comment]
没有原生 API 获取当前函数，tagbar 有提供 `tagbar#currenttag()` 的接口，你可以尝试集成进来。

**Comment by liuchengxu** [comment]
[vista.vim](https://github.com/liuchengxu/vista.vim) 已经实现了这个功能，安装 vista.vim 并拉取最新的 eleline.vim 即可使用，见 #18。
