### ISSUE TITLE
请问eleline支持更换主题么？

### ISSUE THREAD

**Issue by fgheng** [liuchengxu/eleline.vim#20]
我这个主题太暗了，neovim使用的主题是space-vim-dark，然后eleline显示很暗
![image](https://user-images.githubusercontent.com/50551377/60383725-5f43b700-9aa7-11e9-8a20-82331863e746.png)

不知道eleline能否像airline那样更换主题不

**Comment by liuchengxu** [comment]
主题只适配 space-vim-dark 和 space-vim-theme, 其他不支持。
