### ISSUE TITLE
保存文件退出 (:wq) 报错

### ISSUE THREAD

**Issue by sunnirvana** [liuchengxu/eleline.vim#21]
你好，

在编辑文件，保存退出时，会报如下错误，但是文件保存没问题。
Error detected while processing function <SNR>30_on_exit:
line    3:
E716: Key not present in Dictionary: stdout, 'v:val =~ "*"'))
E116: Invalid arguments for function filter
E116: Invalid arguments for function join
E15: Invalid expression: join(filter(self.stdout, 'v:val =~ "*"'))%

搜索后，发现应该是如下代码报错：
function! s:on_exit(job_id, data, _event) dict abort
  if !has_key(s:jobs, a:job_id) | return | endif
  if v:dying | return | endif
  let l:cur_branch = join(filter(self.stdout, 'v:val =~ "*"'))
  if !empty(l:cur_branch)
    let l:branch = substitute(l:cur_branch, '*', s:font ? "  \ue0a0" : ' Git:', '')
    call s:SetGitBranch(self.cwd, l:branch.' ')
  else
    let err = join(self.stderr)
    if !empty(err) | echoerr err | endif
  endif
  call remove(s:jobs, a:job_id)
endfunction

对 vim script 不了解，有空可以帮忙看下吗？谢谢

**Comment by liuchengxu** [comment]
升级 neovim, 版本太低.

**Comment by sunnirvana** [comment]
升级Neovim后，问题还是存在，可以帮忙看下吗？谢谢

Neovim 版本是 0.5.0
![image](https://user-images.githubusercontent.com/511543/67774854-0dcd2800-fa99-11e9-96f2-86764ff7f4a2.png)

在 eleline.vim/plugin/eleline.vim 加了打印信息
![image](https://user-images.githubusercontent.com/511543/67775022-4d940f80-fa99-11e9-8474-94a7613c65f5.png)

打印信息中，self 是有 stdout 的，但报错还是  Key not present in Dictionary: stdout
![image](https://user-images.githubusercontent.com/511543/67775143-75837300-fa99-11e9-89d0-ef65b1d04d08.png)

**Comment by liuchengxu** [comment]
如果你能够提供可以复现的途径，我可以看下，我这里目前无法复现。
