### ISSUE TITLE
Statusline on inactive window is still colorful (not getting gray)

### ISSUE THREAD

**Issue by rockyzhang24** [liuchengxu/eleline.vim#24]
Hi Chengxu,

I stumbled across on this pretty statusline setting and I installed it just now. Now I'm reading the code and trying to configure it. Just one more thing, I found the statusline on the inactive window is the same as the active window (shown below). I know it was extracted from space-vim and I saw the screenshot of space-vim showing that the statusline on the inactive window is totally gray. Is that normal or something wrong on my end? Thank you very much.

![image](https://user-images.githubusercontent.com/11582667/81527555-6f573480-930f-11ea-8cf9-d8da8f225687.png)

**Comment by liuchengxu** [comment]
The color is changed when you are in the insert mode, not for _the inactive window_, see #10.
