### ISSUE TITLE
How to update color schema to match my current vim theme

### ISSUE THREAD

**Issue by henryoliver** [liuchengxu/eleline.vim#28]
Hi there!

Thanks for this lightweight statusline. Clean and useful!

How could I change the colors `s:colors` to match my current theme (Nord) without have to fork eleline.vim. Is there anyway to extend its configuration and overwrite the current colors?

Thank you very much for the help!
Henry

**Comment by rockyzhang24** [comment]
I think you have to fork it and change the color code one by one by yourself.

**Comment by liuchengxu** [comment]
Actually I also want to change the colors at times, but haven't got enough time to look into the design. Happy to see a PR to support this.
