### ISSUE TITLE
MacVim 状态栏图标是不是utf-8编码

### ISSUE THREAD

**Issue by zhenjun115** [liuchengxu/eleline.vim#3]
<img width="682" alt="2017-08-24 10 13 50" src="https://user-images.githubusercontent.com/5096364/29646310-410f3daa-88b5-11e7-980b-19e2afe11c57.png">

你好，请问圆括号包含数字的图标是什么编码的？是utf-8 还是unicode的？这些图标是怎么输入到文件里的？

**Comment by liuchengxu** [comment]
文件类型是 utf-8, 这些符号是 Unicode 字符，怎么输入这些字符可以参考[这里](http://blog.csdn.net/simple_the_best/article/details/52739551)。另外有兴趣的话，还有一些其他资源可以看一下，里面也涉及了一些相关的插件：

- https://www.reddit.com/r/vim/comments/37w34l/simple_way_to_insert_unicode_chars/
- https://vi.stackexchange.com/questions/2254/what-is-the-easiest-way-to-insert-unicode-characters-into-a-document
- http://vim.wikia.com/wiki/Entering_special_characters
