### ISSUE TITLE
No gitblame & coc-diagnostic

### ISSUE THREAD

**Issue by 0x8f701** [liuchengxu/eleline.vim#35]
![image](https://user-images.githubusercontent.com/33961674/98999641-69e5db80-2538-11eb-8ad7-d6e8e1946d36.png)

I just switched from `lightline` to eleline, it works well but I cannot fine `gitblame` and `coc-diagnostic` anymore

My previous lightline config is here:

https://github.com/GopherJ/cfg/blob/master/coc/.vimrc#L499-L527

and my `eleline` config:

```
set laststatus=2
let g:eleline_powerline_fonts = 1
```

**Comment by liuchengxu** [comment]
As the README mentioned, it's encouraged to fork eleline.vim to make your own custom vim statusline if some features are missing in eleline.vim, eleline.vim is a very tiny plugin and not intended to be a full-feature statusline plugin like lightline.
