### ISSUE TITLE
`coc#status` error

### ISSUE THREAD

**Issue by fannheyward** [liuchengxu/eleline.vim#48]
```
处理 function ElelineCoc[5]..coc#status 时发生错误:
第    3 行:
E712: get() 的参数必须是 List 或者 Dictionary
```

> BREAKING CHANGE: variable 'b:coc_diagnostic_info' would be
null after diagnostics clear

https://github.com/neoclide/coc.nvim/commit/8f18641de4cc5b176e800c321389502b89935298

**Comment by liuchengxu** [comment]
This should be resolved in coc.nvim, see https://github.com/neoclide/coc.nvim/pull/3169 .

**Comment by chemzqm** [comment]
That variable would be removed on clear, after https://github.com/neoclide/coc.nvim/commit/24ded9882629ddda40f9640fa754b0613cdc5cde

**Comment by liuchengxu** [comment]
Closing since it's already fixed in coc.nvim.
