### ISSUE TITLE
最新版会导致 vim 默认文字消失

### ISSUE THREAD

**Issue by dalutou** [liuchengxu/eleline.vim#5]
禁用 vim 除 eleline.vim 外的所有插件，vim 默认文字一闪就消失，如下：
<img width="725" alt="qq20171215-162325 2x" src="https://user-images.githubusercontent.com/2087690/34033337-c7ab5ba2-e1b4-11e7-9489-5faba10d076e.png">

禁用 vim 所有插件，默认文字文字正常出现：
<img width="725" alt="qq20171215-162349 2x" src="https://user-images.githubusercontent.com/2087690/34033340-cc81389a-e1b4-11e7-9737-50fb052ffeb6.png">

macOS 10.13.2

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/eleline.vim/blob/master/plugin/eleline.vim#L203-L205

eleline.vim 调用了 `timer_start` 这个定时器 api 进行了延时加载，以免一些原因增加启动时间（虽然可能只是几十毫秒），应该是进入 vim 200 毫秒后调用回调函数导致了欢迎界面的消失。如果你不想要这个功能的话，也可以加选项不启用。

**Comment by dalutou** [comment]
有没有办法既使用延时加载，又保留欢迎界面呢？
