### ISSUE TITLE
Integration error with GitGutter

### ISSUE THREAD

**Issue by hongyuanjia** [liuchengxu/eleline.vim#8]
Whenever I open a file under git version control, Vim always complains an error below:

```vim
Error detected while processing function S_gitgutter:
line 2:
E716: Key not present in Dictionary: summary
```

Any insight?

**Comment by liuchengxu** [comment]
Have you updated [eleline.vim](https://github.com/liuchengxu/eleline.vim) to the latest version? This issue should be fixed in https://github.com/liuchengxu/eleline.vim/commit/683749463947d2865376b17964de0db6968bc061#diff-2a2f0dc560b64279054d1e043506db81R82 .

**Comment by hongyuanjia** [comment]
I am using your vim distribution `space-vim` which uses `eleline` as its default status line plugin. However, it seems like that `eleline` failed to update using `PlugUpdate`. I cannot figure out why.

After I manually run `git pull` in `eleline` plugin folder, the error was gone.

Thanks for your great work for both `eleline` and `Space-Vim`. I love them both.
