### ISSUE TITLE
Missing argument for SetMyStatusline function

### ISSUE THREAD

**Issue by chyla** [liuchengxu/eleline.vim#9]
Hello,
argument for SetMyStatusline is missing. Error will be shown when using Vim older than 7.4 - _else_ part will be executed.

```
if exists('*timer_start')
  call timer_start(100, 'SetMyStatusline')
else
  call SetMyStatusline()
endif
```

https://github.com/liuchengxu/eleline.vim/blob/683749463947d2865376b17964de0db6968bc061/plugin/eleline.vim#L206

**Comment by liuchengxu** [comment]
Should be fixed now.
